In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
dataset=tf.data.Dataset.from_tensor_slices(np.array([[0,1,2,3,4],[5,6,7,8,9]]))

In [3]:
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)


In [4]:
datasets2=dataset.interleave(
lambda v:tf.data.Dataset.from_tensor_slices(v+1)
)

In [5]:
for item in datasets2:
    print(item)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [6]:
kk=pd.DataFrame([['a1','b1','c1','d1',13],['a2','b2','c3','d4',19],['a1','b2','c3','d3',12.3]],columns=['a','b','c','d','e'])
feature_columns=[]

feature_columns.append(tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list('a',kk['a'].unique())))
feature_columns.append(tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list('b',kk['b'].unique())))
feature_columns.append(tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list('c',kk['c'].unique())))
feature_columns.append(tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list('d',kk['d'].unique())))
feature_columns.append(tf.feature_column.numeric_column('e',dtype=tf.float32))

In [7]:
m=dict(kk)
print(m)
print(tf.keras.layers.DenseFeatures(feature_columns)(m).numpy())

{'a': 0    a1
1    a2
2    a1
Name: a, dtype: object, 'b': 0    b1
1    b2
2    b2
Name: b, dtype: object, 'c': 0    c1
1    c3
2    c3
Name: c, dtype: object, 'd': 0    d1
1    d4
2    d3
Name: d, dtype: object, 'e': 0    13.0
1    19.0
2    12.3
Name: e, dtype: float64}
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
[[ 1.   0.   1.   0.   1.   0.   1.   0.   0.  13. ]
 [ 0.   1.   0.   1.   0.   1.   0.   1.   0.  19. ]
 [ 1.   0.   0.   1.   0.   1.   0.   0.   1.  12.3]]
